package tables

import (
	"encoding/binary"
	"fmt"
)

// Code generated by binarygen from aat.go. DO NOT EDIT

func (item *aatExtendedLookupTable) mustParse(src []byte) {
	_ = src[1] // early bound checking
	item.version = binary.BigEndian.Uint16(src[0:])
}

func parseAatExtendedLookupTable(src []byte) (aatExtendedLookupTable, int, error) {
	var item aatExtendedLookupTable
	n := 0
	if L := len(src); L < 2 {
		return aatExtendedLookupTable{}, 0, fmt.Errorf("EOF: expected length: 2, got %d", L)
	}

	item.mustParse(src)
	n += 2
	return item, n, nil
}

func parseAatExtendedStateTable(src []byte) (aatExtendedStateTable, int, error) {
	var item aatExtendedStateTable
	n := 0
	{
		subSlice := src[n:]
		if L := len(subSlice); L < 16 {
			return aatExtendedStateTable{}, 0, fmt.Errorf("EOF: expected length: 16, got %d", L)
		}

		_ = subSlice[15] // early bound checking
		item.stateSize = binary.BigEndian.Uint32(subSlice[0:])
		item.classTable = binary.BigEndian.Uint32(subSlice[4:])
		item.stateArray = binary.BigEndian.Uint32(subSlice[8:])
		item.entryTable = binary.BigEndian.Uint32(subSlice[12:])
		n += 16

	}
	item.data = src[n:]
	n = len(src)

	return item, n, nil
}

func (item *aatLookupTable) mustParse(src []byte) {
	_ = src[1] // early bound checking
	item.version = aatLookupTableVersion(binary.BigEndian.Uint16(src[0:]))
}

func parseAatLookupTable(src []byte) (aatLookupTable, int, error) {
	var item aatLookupTable
	n := 0
	if L := len(src); L < 2 {
		return aatLookupTable{}, 0, fmt.Errorf("EOF: expected length: 2, got %d", L)
	}

	item.mustParse(src)
	n += 2
	return item, n, nil
}

func parseAatLookupTable0(src []byte, valuesLength int) (aatLookupTable0, int, error) {
	var item aatLookupTable0
	n := 0
	{
		subSlice := src[n:]
		if L := len(subSlice); L < +valuesLength*2 {
			return aatLookupTable0{}, 0, fmt.Errorf("EOF: expected length: %d, got %d", +valuesLength*2, L)
		}

		item.values = make([]uint16, valuesLength) // allocation guarded by the previous check
		for i := range item.values {
			item.values[i] = binary.BigEndian.Uint16(subSlice[+i*2:])
		}

		n += valuesLength * 2
	}
	return item, n, nil
}

func parseAatLookupTable10([]byte) (aatLookupTable10, int, error) {
	var item aatLookupTable10
	n := 0
	return item, n, nil
}

func parseAatLookupTable2(src []byte) (aatLookupTable2, int, error) {
	var item aatLookupTable2
	n := 0
	{
		subSlice := src[n:]
		if L := len(subSlice); L < 10 {
			return aatLookupTable2{}, 0, fmt.Errorf("EOF: expected length: 10, got %d", L)
		}

		_ = subSlice[9] // early bound checking
		item.binSearchHeader.mustParse(subSlice[0:])
		n += 10

	}
	{
		subSlice := src[n:]
		arrayLength := int(item.nUnits)
		if L := len(subSlice); L < +arrayLength*6 {
			return aatLookupTable2{}, 0, fmt.Errorf("EOF: expected length: %d, got %d", +arrayLength*6, L)
		}

		item.records = make([]classRangeRecord, arrayLength) // allocation guarded by the previous check
		for i := range item.records {
			item.records[i].mustParse(subSlice[+i*6:])
		}

		n += arrayLength * 6
	}
	return item, n, nil
}

func parseAatLookupTable4([]byte) (aatLookupTable4, int, error) {
	var item aatLookupTable4
	n := 0
	return item, n, nil
}

func parseAatLookupTable6([]byte) (aatLookupTable6, int, error) {
	var item aatLookupTable6
	n := 0
	return item, n, nil
}

func parseAatLookupTable8([]byte) (aatLookupTable8, int, error) {
	var item aatLookupTable8
	n := 0
	return item, n, nil
}

func (item *aatStateEntry0) mustParse(src []byte) {
	_ = src[3] // early bound checking
	item.newState = binary.BigEndian.Uint16(src[0:])
	item.flags = binary.BigEndian.Uint16(src[2:])
}

func parseAatStateEntry0(src []byte) (aatStateEntry0, int, error) {
	var item aatStateEntry0
	n := 0
	if L := len(src); L < 4 {
		return aatStateEntry0{}, 0, fmt.Errorf("EOF: expected length: 4, got %d", L)
	}

	item.mustParse(src)
	n += 4
	return item, n, nil
}

func (item *aatStateEntry2) mustParse(src []byte) {
	_ = src[5] // early bound checking
	item.newState = binary.BigEndian.Uint16(src[0:])
	item.flags = binary.BigEndian.Uint16(src[2:])
	for i := range item.data {
		item.data[i] = src[4+i]
	}
}

func parseAatStateEntry2(src []byte) (aatStateEntry2, int, error) {
	var item aatStateEntry2
	n := 0
	if L := len(src); L < 6 {
		return aatStateEntry2{}, 0, fmt.Errorf("EOF: expected length: 6, got %d", L)
	}

	item.mustParse(src)
	n += 6
	return item, n, nil
}

func (item *aatStateEntry4) mustParse(src []byte) {
	_ = src[7] // early bound checking
	item.newState = binary.BigEndian.Uint16(src[0:])
	item.flags = binary.BigEndian.Uint16(src[2:])
	for i := range item.data {
		item.data[i] = src[4+i]
	}
}

func parseAatStateEntry4(src []byte) (aatStateEntry4, int, error) {
	var item aatStateEntry4
	n := 0
	if L := len(src); L < 8 {
		return aatStateEntry4{}, 0, fmt.Errorf("EOF: expected length: 8, got %d", L)
	}

	item.mustParse(src)
	n += 8
	return item, n, nil
}

func parseAatStateTable(src []byte) (aatStateTable, int, error) {
	var item aatStateTable
	n := 0
	{
		subSlice := src[n:]
		if L := len(subSlice); L < 8 {
			return aatStateTable{}, 0, fmt.Errorf("EOF: expected length: 8, got %d", L)
		}

		_ = subSlice[7] // early bound checking
		item.stateSize = binary.BigEndian.Uint16(subSlice[0:])
		item.classTable = binary.BigEndian.Uint16(subSlice[2:])
		item.stateArray = binary.BigEndian.Uint16(subSlice[4:])
		item.entryTable = binary.BigEndian.Uint16(subSlice[6:])
		n += 8

	}
	item.data = src[n:]
	n = len(src)

	return item, n, nil
}

func (item *binSearchHeader) mustParse(src []byte) {
	_ = src[9] // early bound checking
	item.unitSize = binary.BigEndian.Uint16(src[0:])
	item.nUnits = binary.BigEndian.Uint16(src[2:])
	item.searchRange = binary.BigEndian.Uint16(src[4:])
	item.entrySelector = binary.BigEndian.Uint16(src[6:])
	item.rangeShift = binary.BigEndian.Uint16(src[8:])
}

func parseBinSearchHeader(src []byte) (binSearchHeader, int, error) {
	var item binSearchHeader
	n := 0
	if L := len(src); L < 10 {
		return binSearchHeader{}, 0, fmt.Errorf("EOF: expected length: 10, got %d", L)
	}

	item.mustParse(src)
	n += 10
	return item, n, nil
}

func (item *classRangeRecord) mustParse(src []byte) {
	_ = src[5] // early bound checking
	item.start = glyphID(binary.BigEndian.Uint16(src[0:]))
	item.end = glyphID(binary.BigEndian.Uint16(src[2:]))
	item.value = binary.BigEndian.Uint16(src[4:])
}

func parseClassRangeRecord(src []byte) (classRangeRecord, int, error) {
	var item classRangeRecord
	n := 0
	if L := len(src); L < 6 {
		return classRangeRecord{}, 0, fmt.Errorf("EOF: expected length: 6, got %d", L)
	}

	item.mustParse(src)
	n += 6
	return item, n, nil
}
