package tables

import (
	"encoding/binary"
	"fmt"
)

// Code generated by binarygen from glyphs_misc_src.go. DO NOT EDIT

func ParseSVG(src []byte) (SVG, int, error) {
	var item SVG
	n := 0
	if L := len(src); L < 10 {
		return item, 0, fmt.Errorf("reading SVG: "+"EOF: expected length: 10, got %d", L)
	}
	_ = src[9] // early bound checking
	item.version = binary.BigEndian.Uint16(src[0:])
	offsetItemSVGDocumentList := int(binary.BigEndian.Uint32(src[2:]))
	item.reserved = binary.BigEndian.Uint32(src[6:])
	n += 10

	{

		if offsetItemSVGDocumentList != 0 { // ignore null offset
			if L := len(src); L < offsetItemSVGDocumentList {
				return item, 0, fmt.Errorf("reading SVG: "+"EOF: expected length: %d, got %d", offsetItemSVGDocumentList, L)
			}

			var (
				err  error
				read int
			)
			item.SVGDocumentList, read, err = ParseSVGDocumentList(src[offsetItemSVGDocumentList:])
			if err != nil {
				return item, 0, fmt.Errorf("reading SVG: %s", err)
			}
			offsetItemSVGDocumentList += read

		}
	}
	return item, n, nil
}

func ParseSVGDocumentList(src []byte) (SVGDocumentList, int, error) {
	var item SVGDocumentList
	n := 0
	if L := len(src); L < 2 {
		return item, 0, fmt.Errorf("reading SVGDocumentList: "+"EOF: expected length: 2, got %d", L)
	}
	arrayLengthItemDocumentRecords := int(binary.BigEndian.Uint16(src[0:]))
	n += 2

	{

		if L := len(src); L < 2+arrayLengthItemDocumentRecords*12 {
			return item, 0, fmt.Errorf("reading SVGDocumentList: "+"EOF: expected length: %d, got %d", 2+arrayLengthItemDocumentRecords*12, L)
		}

		item.DocumentRecords = make([]SVGDocumentRecord, arrayLengthItemDocumentRecords) // allocation guarded by the previous check
		for i := range item.DocumentRecords {
			item.DocumentRecords[i].mustParse(src[2+i*12:])
		}
		n += arrayLengthItemDocumentRecords * 12
	}
	{

		item.SVGRawData = src[0:]
		n = len(src)
	}
	return item, n, nil
}

func (item *SVGDocumentRecord) mustParse(src []byte) {
	_ = src[11] // early bound checking
	item.StartGlyphID = GlyphID(binary.BigEndian.Uint16(src[0:]))
	item.EndGlyphID = GlyphID(binary.BigEndian.Uint16(src[2:]))
	item.SvgDocOffset = Offset32(binary.BigEndian.Uint32(src[4:]))
	item.SvgDocLength = binary.BigEndian.Uint32(src[8:])
}
